### ISSUE TITLE
project doesn't follow Go's project structure conventions

### ISSUE THREAD

**Issue by pashagolub** [destrex271/pgwatch3_rpc_server#14]
It is recommended to move the Go files to the root directory of your project.
Now I see three level structure for no reason.

The link doesn't reflect standard per se, but I put it here as a starting point.
https://github.com/golang-standards/project-layout

We can have even [simpler structure](https://github.com/golang-standards/project-layout/issues/117)

**Comment by destrex271** [comment]
Cool, I'll check these out. Thanks!

**Comment by pashagolub** [comment]
1. There is no value in `dummy_client` as a standalone application
2. Functionality should be moved to test cases
3. Final repository structure **must** be like this:

```
root
|-sinks
  |- common.go      <-- I don't see any value here as well but we can discuss
  |- common_test.go <-- here we use code from dummy_client 
  |- types.go
|-cmd
  |- csv_receiver
    |- main.go
    |- ...
  |- text_receiver
    |- main.go
    |- ...
  |- parquet_receiver
    |- main.go
    |- ...
go.mod
go.sum
README.md
...
```

These are the **requirements** for successful project evaluation:
1. One and only `go.mod` for repository.
2. `go.mod` should contain full name (including github.com) instead of just `module pgwatch3_rpc_receiver`
3. Every `cmd` using `sinks` **must** import it by absolute URL, e.g. `import github.com/destrex271/pgwatch3_rpc_server/sinks` or we must get rid of `sinks` package at all.
4. Every binary is build with `go build ./cmd/csv_receiver`
5. I want code covered with tests cases

What is cool to have:
1. Readme badges
2. Godoc documentation
3. Github Actions workflows with testing and coverage stats
4. Goreleaser workflow for binaries and releases
5.

**Comment by destrex271** [comment]
Okk, I'll add these

**Comment by destrex271** [comment]
Are we sure about keeping separate main.go files?

**Comment by pashagolub** [comment]
I am sure, yes! This is how I want to see different implementations. What are reasons to have them as one binary?

**Comment by destrex271** [comment]
My original idea was to keep this main.go file as the central part of the project. If someone writes a sink they can contribute back to the project by just adding a single condition to the file.

**Comment by destrex271** [comment]
But looking back I think it doesn't make that much of a difference tho, I'll add separate main.go files.

**Comment by destrex271** [comment]
This way the user will just need to add a conditional to the main.go file and they can easily run their sinks as:

`go run . --type=<sink_type> --port=<port>`

**Comment by pashagolub** [comment]
> My original idea was to keep this main.go file as the central part of the project. If someone writes a sink they can contribute back to the project by just adding a single condition to the file.

Don't think so. People tend to create their own repo for new implementations. I don't see any crucial parts that I want to use in a brand new RPC implementation.

**Comment by pashagolub** [comment]
Excerpt from **https://en.wikipedia.org/wiki/Unix_philosophy**:

It was later summarized by [Peter H. Salus](https://en.wikipedia.org/wiki/Peter_H._Salus) in A Quarter-Century of Unix (1994):[[1]](https://en.wikipedia.org/wiki/Unix_philosophy#cite_note-taoup-ch1s6-1)

    Write programs that do one thing and do it well.
    Write programs to work together.
    Write programs to handle text streams, because that is a universal interface.

That's what I'm trying to achieve. :-)

**Comment by destrex271** [comment]
Sure added separate files to the Pull Request!

**Comment by destrex271** [comment]
Solved in the following PRs:
 - #19
 - #17 
 -  #15 

We can reopen this issue again if there are any other changes required, marking this as completed for now
