### ISSUE TITLE
CSV Reciever

### ISSUE THREAD

**Issue by destrex271** [destrex271/pgwatch3_rpc_server#2]
An RPC receiver that accepts the measurements and writes them to a csv file as specified in the request url

**Comment by pashagolub** [comment]
I prefer to use measurements term. Meaning metric is a definition (schema) of what we fetch. And a real metric data fetched is a measurement. 

Just like temperature Celsius is a metric, but 45°С is a measurement of temperature. :-)

**Comment by destrex271** [comment]
Ok, Will make that change

**Comment by destrex271** [comment]
Completed, closing this issue.
